name: ETL pipeline CI/CD

on:
  #push:
  #  branches:
  #    - main

  workflow_dispatch:

jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Dev
        run: echo "Deploying to ${{ vars.ENV_DEV }} environment"

  deploy_uat:
    runs-on: ubuntu-latest
    environment: UAT
    needs: deploy_dev
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to UAT
        run: echo "Deploying to ${{ secrets.ENV_UAT }} environment"

  deploy_prod:
    runs-on: ubuntu-latest
    environment: PROD
    needs: deploy_uat
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Prod
        run: echo "Deploying to ${{ vars.ENV_PROD }} environment"

