name: Deploy to Dev

on:
  push:
    branches:
      - main

jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Dev
        run: echo "Deploying to Dev environment"

  deploy_uat:
    runs-on: ubuntu-latest
    environment: UAT
    needs: deploy_dev
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to UAT
        run: echo "Deploying to UAT environment"

  deploy_prod:
    runs-on: ubuntu-latest
    environment: PROD
    needs: deploy_uat
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Prod
        run: echo "Deploying to Prod environment"

